package namespacecheck

import (
	"k8s.io/apimachinery/pkg/util/sets"
)

// TODO these could be hardcoded in a different package or repo and simply checked here.
var (
	AllKnownNamespaces = sets.NewString(
		"default",
		"kube-system",
		"openshift",
		"openshift-apiserver",
		"openshift-apiserver-operator",
		"openshift-authentication",
		"openshift-authentication-operator",
		"openshift-cloud-controller-manager",
		"openshift-cloud-controller-manager-operator",
		"openshift-cloud-credential-operator",
		"openshift-cloud-network-config-controller",
		"openshift-cluster-csi-drivers",
		"openshift-cluster-machine-approver",
		"openshift-cluster-node-tuning-operator",
		"openshift-cluster-samples-operator",
		"openshift-cluster-storage-operator",
		"openshift-cluster-version",
		"openshift-config",
		"openshift-config-managed",
		"openshift-config-operator",
		"openshift-console",
		"openshift-console-operator",
		"openshift-controller-manager",
		"openshift-controller-manager-operator",
		"openshift-dns",
		"openshift-dns-operator",
		"openshift-etcd",
		"openshift-etcd-operator",
		"openshift-host-network",
		"openshift-image-registry",
		"openshift-ingress",
		"openshift-ingress-canary",
		"openshift-ingress-operator",
		"openshift-insights",
		"openshift-kni-infra",
		"openshift-kube-apiserver",
		"openshift-kube-apiserver-operator",
		"openshift-kube-controller-manager",
		"openshift-kube-controller-manager-operator",
		"openshift-kube-scheduler",
		"openshift-kube-scheduler-operator",
		"openshift-kube-storage-version-migrator",
		"openshift-kube-storage-version-migrator-operator",
		"openshift-machine-api",
		"openshift-machine-config-operator",
		"openshift-marketplace",
		"openshift-monitoring",
		"openshift-multus",
		"openshift-network-diagnostics",
		"openshift-network-operator",
		"openshift-nutanix-infra",
		"openshift-oauth-apiserver",
		"openshift-openstack-infra",
		"openshift-operator-lifecycle-manager",
		"openshift-operators",
		"openshift-ovirt-infra",
		"openshift-ovn-kubernetes",
		"openshift-service-ca",
		"openshift-service-ca-operator",
		"openshift-user-workload-monitoring",
		"openshift-vsphere-infra",
	)

	NamespacesToJiraComponents = map[string]string{
		"default":                                          "kube-apiserver",
		"kube-system":                                      "kube-apiserver",
		"openshift":                                        "kube-apiserver",
		"openshift-apiserver":                              "openshift-apiserver",
		"openshift-apiserver-operator":                     "openshift-apiserver",
		"openshift-authentication":                         "apiserver-auth",
		"openshift-authentication-operator":                "apiserver-auth",
		"openshift-cloud-controller-manager":               "Cloud Compute / Cloud Controller Manager",
		"openshift-cloud-controller-manager-operator":      "Cloud Compute / Cloud Controller Manager",
		"openshift-cloud-credential-operator":              "Cloud Credential Operator",
		"openshift-cloud-network-config-controller":        "Networking / cloud-network-config-controller",
		"openshift-cluster-csi-drivers":                    "Storage",
		"openshift-cluster-machine-approver":               "Cloud Compute / Other Provider",
		"openshift-cluster-node-tuning-operator":           "Node Tuning Operator",
		"openshift-cluster-samples-operator":               "Samples Operator",
		"openshift-cluster-storage-operator":               "Storage",
		"openshift-cluster-version":                        "Cluster Version Operator",
		"openshift-config":                                 "kube-apiserver",
		"openshift-config-managed":                         "kube-apiserver",
		"openshift-config-operator":                        "config-operator",
		"openshift-console":                                "Management Console",
		"openshift-console-operator":                       "Management Console",
		"openshift-controller-manager":                     "openshift-controller-manager / controller-manager",
		"openshift-controller-manager-operator":            "openshift-controller-manager / controller-manager",
		"openshift-dns":                                    "Networking / DNS",
		"openshift-dns-operator":                           "Networking / DNS",
		"openshift-etcd":                                   "Etcd",
		"openshift-etcd-operator":                          "Etcd",
		"openshift-host-network":                           "Networking / cluster-network-operator",
		"openshift-image-registry":                         "Image Registry",
		"openshift-ingress":                                "Networking / router",
		"openshift-ingress-canary":                         "Networking / router",
		"openshift-ingress-operator":                       "Networking / router",
		"openshift-insights":                               "Insights Operator",
		"openshift-kni-infra":                              "Networking / cluster-network-operator",
		"openshift-kube-apiserver":                         "kube-apiserver",
		"openshift-kube-apiserver-operator":                "kube-apiserver",
		"openshift-kube-controller-manager":                "kube-controller-manager",
		"openshift-kube-controller-manager-operator":       "kube-controller-manager",
		"openshift-kube-scheduler":                         "kube-scheduler",
		"openshift-kube-scheduler-operator":                "kube-scheduler",
		"openshift-kube-storage-version-migrator":          "kube-storage-version-migrator",
		"openshift-kube-storage-version-migrator-operator": "kube-storage-version-migrator",
		"openshift-machine-api":                            "Cloud Compute / Other Provider",
		"openshift-machine-config-operator":                "Machine Config Operator",
		"openshift-marketplace":                            "OLM",
		"openshift-monitoring":                             "Monitoring",
		"openshift-multus":                                 "Networking / multus",
		"openshift-network-diagnostics":                    "Networking / cluster-network-operator",
		"openshift-network-operator":                       "Networking / cluster-network-operator",
		"openshift-nutanix-infra":                          "Installer / Nutanix",
		"openshift-oauth-apiserver":                        "oauth-apiserver",
		"openshift-openstack-infra":                        "Machine Config Operator / platform-openstack",
		"openshift-operator-lifecycle-manager":             "OLM",
		"openshift-operators":                              "OLM",
		"openshift-operator-controller":                    "OLM",
		"openshift-cluster-olm-operator":                   "OLM",
		"openshift-rukpak":                                 "OLM",
		"openshift-ovirt-infra":                            "Machine Config Operator / platform-ovirt-rhv",
		"openshift-ovn-kubernetes":                         "Networking / ovn-kubernetes",
		"openshift-service-ca":                             "service-ca",
		"openshift-service-ca-operator":                    "service-ca",
		"openshift-user-workload-monitoring":               "Monitoring",
		"openshift-vsphere-infra":                          "Machine Config Operator / platform-vsphere",
	}

	JiraComponentsToNamespaces = map[string][]string{
		"Cloud Compute / Cloud Controller Manager": {
			"openshift-cloud-controller-manager",
			"openshift-cloud-controller-manager-operator",
		},
		"Cloud Compute / Other Provider": {
			"openshift-cluster-machine-approver",
			"openshift-machine-api",
		},
		"Cloud Credential Operator": {
			"openshift-cloud-credential-operator",
		},
		"Cluster Version Operator": {
			"openshift-cluster-version",
		},
		"Etcd": {
			"openshift-etcd",
			"openshift-etcd-operator",
		},
		"Image Registry": {
			"openshift-image-registry",
		},
		"Insights Operator": {
			"openshift-insights",
		},
		"Installer / Nutanix": {
			"openshift-nutanix-infra",
		},
		"Machine Config Operator": {
			"openshift-machine-config-operator",
		},
		"Machine Config Operator / platform-openstack": {
			"openshift-openstack-infra",
		},
		"Machine Config Operator / platform-ovirt-rhv": {
			"openshift-ovirt-infra",
		},
		"Machine Config Operator / platform-vsphere": {
			"openshift-vsphere-infra",
		},
		"Management Console": {
			"openshift-console",
			"openshift-console-operator",
		},
		"Monitoring": {
			"openshift-monitoring",
			"openshift-user-workload-monitoring",
		},
		"Networking / DNS": {
			"openshift-dns",
			"openshift-dns-operator",
		},
		"Networking / cloud-network-config-controller": {
			"openshift-cloud-network-config-controller",
		},
		"Networking / cluster-network-operator": {
			"openshift-host-network",
			"openshift-kni-infra",
			"openshift-network-diagnostics",
			"openshift-network-operator",
		},
		"Networking / multus": {
			"openshift-multus",
		},
		"Networking / ovn-kubernetes": {
			"openshift-ovn-kubernetes",
		},
		"Networking / router": {
			"openshift-ingress",
			"openshift-ingress-canary",
			"openshift-ingress-operator",
		},
		"Node Tuning Operator": {
			"openshift-cluster-node-tuning-operator",
		},
		"OLM": {
			"openshift-marketplace",
			"openshift-operator-lifecycle-manager",
			"openshift-operators",
			"openshift-operator-controller",
			"openshift-cluster-olm-operator",
			"openshift-rukpak",
		},
		"Samples Operator": {
			"openshift-cluster-samples-operator",
		},
		"Storage": {
			"openshift-cluster-csi-drivers",
			"openshift-cluster-storage-operator",
		},
		"apiserver-auth": {
			"openshift-authentication",
			"openshift-authentication-operator",
		},
		"config-operator": {
			"openshift-config-operator",
		},
		"kube-apiserver": {
			"default",
			"kube-system",
			"openshift",
			"openshift-config",
			"openshift-config-managed",
			"openshift-kube-apiserver",
			"openshift-kube-apiserver-operator",
		},
		"kube-controller-manager": {
			"openshift-kube-controller-manager",
			"openshift-kube-controller-manager-operator",
		},
		"kube-scheduler": {
			"openshift-kube-scheduler",
			"openshift-kube-scheduler-operator",
		},
		"kube-storage-version-migrator": {
			"openshift-kube-storage-version-migrator",
			"openshift-kube-storage-version-migrator-operator",
		},
		"oauth-apiserver": {
			"openshift-oauth-apiserver",
		},
		"openshift-apiserver": {
			"openshift-apiserver",
			"openshift-apiserver-operator",
		},
		"openshift-controller-manager / controller-manager": {
			"openshift-controller-manager",
			"openshift-controller-manager-operator",
		},
		"service-ca": {
			"openshift-service-ca",
			"openshift-service-ca-operator",
		},
	}
)
